---
- name: Deploy Nginx to GKE
  hosts:   # Replace with your GKE cluster name
  become: true
  tasks:
    - name: Create a namespace for Nginx
      kubernetes:
        name: nginx
        state: present

    - name: Deploy Nginx deployment
      kubernetes:
        name: nginx-deployment
        state: present
        manifest:
          api_version: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 2  # Adjust replica count
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest  # Replace with your Nginx image
                  ports:
                  - containerPort: 80

    - name: Expose Nginx deployment as a Service
      kubernetes:
        name: nginx-service
        state: present
        manifest:
          api_version: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            selector:
              app: nginx
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80